### ISSUE TITLE
Fixing the URL for sending an invite to join the org

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-core#89]
As of right now in Production when you send an invite from the users section to someone to join they most do not get the email and those who do get an invalid URL to click on to join.

**Comment by glind** [comment]
@odenypeter is this done?

**Comment by glind** [comment]
![Image](https://github.com/buildly-release-management/buildly-core/assets/449810/eff47575-0760-4445-bbfb-c856d25df6cf)



![Image](https://github.com/buildly-release-management/buildly-core/assets/449810/1d603a6c-3cd2-40c2-b470-b05ba78a040d)

**Comment by patelradhika** [comment]
@odenypeter The orange button does not have the correct link for the invite.

![Image](https://github.com/buildly-release-management/buildly-core/assets/64517071/c63a8d7b-0300-4d22-bcde-8f1ff9234c3b)

**Comment by patelradhika** [comment]
Peter has bypassed the sendgrid check for now. So it does work now.
